# Generated by Django 3.2.16 on 2023-10-06 15:14

import django.db.models.deletion
import oscar.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0014_line_date_updated'),
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketBillingInformation',
            fields=[
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=64, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('line3', models.CharField(blank=True, max_length=255, verbose_name='Third line of address')),
                ('line4', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State/County')),
                ('postcode', oscar.models.fields.UppercaseCharField(blank=True, max_length=64, verbose_name='Post/Zip-code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basket_billing_information', serialize=False, to='basket.basket')),
                ('vatin', models.CharField(help_text='The value-added tax identification number or VAT identification number can be used to identify a business or a taxable person in the European Union.', max_length=255, verbose_name='VAT Identification Number (VATIN)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'abstract': False,
            },
        ),
    ]
