# Generated by Django 3.2.16 on 2023-11-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nau_extensions', '0003_auto_20231010_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskettransactionintegration',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
